default:

  contentType: 'application/vnd.api+json'
  popeye: /usr/local/bin/py

#----------------------------------------------------------------------
development:
  local: yes

#----------------------------------------------------------------------
production:

  popeye: /app/vendor/bin/py

#----------------------------------------------------------------------

