default:

  zappa_params:
    port: 3443
    disable_io: yes

  https:
    cert: ./cert/self-signed-certificate.pem
    key:  ./cert/server.key

  key:
    tree: 8ec86790bb6a818a2f7298dc03eedd514b44d72bd13c0b91

  api:
    domain: X-Domain
    token: X-Token

  mongodb:
    uri: mongodb://heroku_app11794599:4c39g6iubaudnct34m0r2jllrr@ds031877.mongolab.com:31877/heroku_app11794599

  validDomains:
    - .localnet

  maxTreeSize: 5000000

#----------------------------------------------------------------------
development:
  local: yes

#----------------------------------------------------------------------
staging:
  validDomains:
    - .staging.config.ly

#----------------------------------------------------------------------
production:

  zappa_params:
    port: 443

  https: no
  #cert: ./cert/production-certificate.pem

  validDomains:
    - .config.ly
    - .config.li

#----------------------------------------------------------------------
test:
  mongodb:
    uri: mongodb://localhost

