default:

  # zappa_params:
  #   port: 3443
  #   disable_io: no


  contentType: 'application/vnd.api+json'
  popeye: '/usr/local/bin/py'

#----------------------------------------------------------------------
development:
  local: yes
  redis: 'redis://localhost'

#----------------------------------------------------------------------
production:

  redis: process.env.REDIS_URL
  zappa_params:
    port: 5000
    # port: /var/run/proxy.sock/node-configly-api.443

#----------------------------------------------------------------------
test:
  mongodb:
    uri: mongodb://localhost

